"""Audit event types — 13 lifecycle events."""

from __future__ import annotations

from enum import StrEnum


class AuditEventType(StrEnum):
    """Execution lifecycle events."""

    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    IDENTITY_RESOLVED = "IDENTITY_RESOLVED"
    DELEGATION_VALIDATED = "DELEGATION_VALIDATED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    RISK_CALCULATED = "RISK_CALCULATED"
    BUDGET_RESERVED = "BUDGET_RESERVED"
    SECURITY_CHECKED = "SECURITY_CHECKED"
    DECISION_MADE = "DECISION_MADE"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    RESULT_INSPECTED = "RESULT_INSPECTED"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
